### ISSUE TITLE
Test262 treats passing tests as failures

### ISSUE THREAD

**Issue by BobVarioa** [CanadaHonk/porffor#152]
I honestly don't know how to reproduce this issue, but sometimes the Test262 runner will list a test under the "new fails" list and mark it as a failure, but if you use `node test262 ./test_path` to run the test individually it says the test was a success.
My best guess is that it has something to do with concurrency, as this is so on and off

**Comment by BobVarioa** [comment]
Actually, after running something with `--threads=1` it still marks various tests as failures, so perhaps it doesn't have much to do with concurrency? There could still be issues definitely, but it should be able to keep up with only one thread

**Comment by CanadaHonk** [comment]
There are a few flaky timeout tests I'm aware of, could be those?

**Comment by BobVarioa** [comment]
I'm pretty sure it's not that because it was over half of the results as failures and most of them were compile errors.
I think it might've been some issue about state transfering between runs, i.e. my fault. I think I might've fixed it, but I'm running test262 to check right now.
I'll close this issue if it ends up being that 😓
