### ISSUE TITLE
--gc-sections not a supported option in LLVM/Apple Clang on macOS, blocking compilation

### ISSUE THREAD

**Issue by lockieluke** [CanadaHonk/porffor#161]
# Issue

`porffor native main.ts main` does not work on macOS:

<img width="549" alt="image" src="https://github.com/user-attachments/assets/65666740-1289-4927-bb3a-c3f94386465b">

```ts
// main.ts
const message: string = "HELLO WORLD";

console.log(message);
```

Clang command generated by porffor:
```bash
clang porffor_tmp.c -o main -Ofast -flto=thin -march=native -s -ffast-math -fno-exceptions -fno-ident -fno-asynchronous-unwind-tables -ffunction-sections -fdata-sections -Wl,--gc-sections
```

According to [this issue](https://github.com/RIOT-OS/RIOT/issues/5787), `--gc-sections` is not supported on macOS, it therefore has to be replaced by `-dead_strip`, rerunning the command with the new option allows compilation:
<img width="545" alt="image" src="https://github.com/user-attachments/assets/354e9940-534a-4d16-bbe6-a0b329b8a8ae">

New clang command:

```bash
clang porffor_tmp.c -o main -Ofast -flto=thin -march=native -s -ffast-math -fno-exceptions -fno-ident -fno-asynchronous-unwind-tables -ffunction-sections -fdata-sections -Wl,-dead_strip
```

`./main` output:

<img width="418" alt="image" src="https://github.com/user-attachments/assets/826b0764-8ba4-4bd5-963b-283dfc3a8aab">

# Potential solution

Conditionally replace `--gc-sections` with `-dead_strip` on Apple Platforms:
https://github.com/CanadaHonk/porffor/blob/303acf5a8faaeeea4bb5027c3c42c5233f92f21a/compiler/index.js#L208

**Comment by CanadaHonk** [comment]
Thanks for the report! Just removed it completely in 3ef35b11079d8877f56953d7144a0d7b166907ba as probably unnecessary.
