### ISSUE TITLE
SyntaxError: 'import' and 'export' may appear only with 'sourceType: module' 

### ISSUE THREAD

**Issue by jcubic** [CanadaHonk/porffor#167]
Got this error when trying to compile a file inside ES Module project.

**Comment by CanadaHonk** [comment]
You can use `--module` to parse input as modules, but ESM isn't supported yet.

**Comment by jcubic** [comment]
Oh, any plans of adding ES Modules?

**Comment by CanadaHonk** [comment]
Definitely! Just longer-term (focusing on core engine currently). See #131.

**Comment by jcubic** [comment]
Any preferred (or easiest) way to compile a file from ESM into CommonJS, so Porffor can work?

If this works, it can be added to docs and ESM support don't need to be implemented.
