### ISSUE TITLE
Fibonacci example generates unexpectedly large output

### ISSUE THREAD

**Issue by rajsite** [CanadaHonk/porffor#173]
The current fibonacci example on `https://porffor.dev/` with content:

```js
let a = 0, b = 1;
Porffor.numberLog(a); Porffor.numberLog(b);

for (let i = 2; i <= 45; i++) {
  let t = b + a;
  a = b;
  b = t;

  Porffor.numberLog(t);
}
```

Compiles out to 323265 bytes.

If I break out some asm.js ideas buried in the back of my head and tweak it like:
```js
let a = 0, b = 1;
Porffor.numberLog(a); Porffor.numberLog(b);

for (let i = 2; i <= 45; i++) {
  let t = b|0 + a; // could alternatively do `+b + a`
  a = b;
  b = t;

  Porffor.numberLog(t);
}
```

Compiles out to 341 bytes.

Seems like compiled output size would be interesting to track as 262 compliance goes up.

**Comment by CanadaHonk** [comment]
Yep this is a bug of it including much more built-ins than needed and not doing the best type tracking

**Comment by rajsite** [comment]
Couple related observations:

- Looks like Array Reading is also generating quote a bit of output 323578 bytes
- I'm guessing the syntax highlighting or something is slowing down the page for the larger generations / making my chrome tab crash. Might be helpful to show it plaintext / limit the output size if it's too large.

**Comment by Rob23oba** [comment]
Well, there's not much optimization currently since that's not really the focus right now. In the future such code should compile again to reasonable sizes.

**Comment by CanadaHonk** [comment]
Still not amazing but the same code now compiles to 74307 bytes instead of the huge size of before.

**Comment by rajsite** [comment]
Maybe a [custom font with built-in syntax highlighting ](https://blog.glyphdrawing.club/font-with-built-in-syntax-highlighting/)will help with rendering large output a bit. 🤯
Need more [porffor wasm in my fonts](https://github.com/harfbuzz/harfbuzz-wasm-examples). 🔥

**Comment by rajsite** [comment]
Today the fibonacci example is 313 bytes! Amazing progress (generally) and porffor is still WIP so no particuuular reason to keep this issue open! Excited to see where it all goes!
