### ISSUE TITLE
Add native run mode

### ISSUE THREAD

**Issue by CanadaHonk** [CanadaHonk/porffor#36]
Add a `run` mode which uses our Wasm->C->native setup instead of host runtime Wasm engine (`run --native`?). Slower compile time, more unstable, better performance at runtime time?

**Comment by xyloflake** [comment]
I think it would be similar to `cargo run` and that would be honestly very good

**Comment by CanadaHonk** [comment]
You can now do `porf --native ...` to run like normal but using the native target (compiles to a native binary and executes it immediately).
