### ISSUE TITLE
ternary operator in return case don't compile

### ISSUE THREAD

**Issue by Manu1400** [CanadaHonk/porffor#4]
### Reproduction steps
1. Open https://porffor.goose.icu/
2. Copy-pasted the following code
```js
function myFunction(number) {
  return number === 0 ? "a" : "k";
}
```
4. set parser: acorn
5. set target: c

**Comment by CanadaHonk** [comment]
C output is experimental at the moment and doesn't support strings yet :P

**Comment by CanadaHonk** [comment]
I am pretty sure this was fixed a few months ago :)
