### ISSUE TITLE
JS Managed Indirect calls

### ISSUE THREAD

**Issue by BobVarioa** [CanadaHonk/porffor#96]
Based on a somewhat similar approach by the Emscriptem developers, this would basically be an import that does something like the following:
```js
function call_indirect(idx: number, args: any[]) {
    // check new.target, this arg, rest params, etc.
    return funcs[idx](...args)
}
```
Then, WASM would pack it's imports into an array and call the import. 

This also would likely make #95 much easier.

The major caveat here, however, is that all WASM functions would have to be exported

**Comment by CanadaHonk** [comment]
Happy with new indirect system which isn't this but kind of related, can reopen if not later
